"use client"
// import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import "@cloudscape-design/global-styles/index.css"
import I18nProvider from "@cloudscape-design/components/i18n";
import { AppLayout, ContentLayout, Flashbar, HelpPanel } from "@cloudscape-design/components";
import messages from "@cloudscape-design/components/i18n/messages/all.all";

import TQHeader from "./components/TQHeader"

import SIdebar from './components/SIdeBar'
const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };


export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <I18nProvider messages={[messages]}>
      <TQHeader/>
    {/* <TQFHeader/> */}
      <AppLayout
      
        // breadcrumbs={
        // //   <BreadcrumbGroup
        // //     items={[
        // //       { text: 'Home', href: '#' },
        // //       { text: 'Service', href: '#' },
        // //     ]}
        // //   />
        // // }
        // navigationOpen={}
        navigation={
         <SIdebar/>
        }
        notifications={
          <Flashbar
            items={[
              {
                type: 'info',
                dismissible: true,
                content: 'This is an info flash message.',
                id: 'message_1',
              },
            ]}
          />
        }
        // toolsOpen={true}
        tools={<HelpPanel header={<h2>Notifications</h2>}>

          {/* <NotificationBar/> */}
        </HelpPanel>
        
      }
      
        content={
          <ContentLayout
            // header={
            //   <Header variant="h1" info={<Link variant="info">Info</Link>}>
            //     Page header
            //   </Header>
            // }
          >
          {children}
          </ContentLayout>
        }
        // splitPanel={<SplitPanel header="Split panel header">Split panel content</SplitPanel>}
      />
    </I18nProvider>
        </body>
    </html>
  );
}